export const lifeAtDeptImages = [
  { src: "/gallery/1.jpeg" },
  { src: "/gallery/2.jpeg" },
  { src: "/gallery/3.jpeg" },
  { src: "/gallery/4.jpeg" },
  { src: "/gallery/5.jpeg" },
  { src: "/gallery/6.jpeg" },
  { src: "/gallery/7.jpeg" },
  { src: "/gallery/8.jpeg" },
  { src: "/gallery/9.jpeg" },
  { src: "/gallery/10.jpeg" },
  { src: "/gallery/11.jpeg" },
  { src: "/gallery/12.jpeg" },
  { src: "/gallery/13.jpeg" },
  { src: "/gallery/14.jpeg" },
  { src: "/gallery/15.jpeg" },
  { src: "/gallery/16.jpeg" },
  { src: "/gallery/17.jpeg" },
  { src: "/gallery/18.jpeg" },
  { src: "/gallery/19.jpeg" },
  { src: "/gallery/21.jpeg" },
  { src: "/gallery/22.jpeg" },
  { src: "/gallery/23.jpeg" },
  { src: "/gallery/24.jpeg" },
  { src: "/gallery/25.jpeg" },
  { src: "/gallery/27.jpeg" },
];
