export const eventsData = [


  {
    id: 16,
    title: "Research Talk by Dr. Sashmita Panda",
    type: "seminar",
    displayDate: "October 29, 2025",
    date: "2025-10-29",
    description: "Title: Single Neuron And Population Approaches For Evaluating Excitatory Neuronopathy In Scn2a-Related Disorder.",
    affiliation: "Postdoctoral Fellow, Department of Neurology, Northwestern University's Feinberg School of Medicine, Chicago, USA.",
    eventlink: "LHC-09",
    isLatest: false,
  },
  {
    id: 16,
    title: "Research Talk by Prof. Manish Kumar",
    type: "seminar",
    displayDate: "October 29, 2025",
    date: "2025-10-29",
    description: "Title: Illustrating Phenotype Diversity with Gene Repertoires via Multi-Omics Analyses.",
    affiliation: "Department of Biophysics, University of Delhi (South Campus), New Delhi.",
    eventlink: "",
    venue: "LHC-01",
    isLatest: false,
  },
    {
    id: 15,
    title: "Talk by Dr. Sanita Mukhopadhyay, FNA, FASc, FNASc, FTASc, JC Bose Fellow, Tata Innovation Fellow",
    type: "seminar",
    displayDate: "October 27, 2025",
    date: "2025-10-27",
    description: "Title: Tuberculosis- Lessons Learned and Future Trends",
    affiliation: "",
    eventlink: "",
    venue: "LHC-03",
    isLatest: false,
  },
    {
    id: 14,
    title: "Industry Talk by Dr. Megha Abbey",
    type: "seminar",
    displayDate: "October 24, 2025",
    date: "2025-10-24",
    description: "Title: Biologics by Biologists.",
    affiliation: "Biosimilars Professional, Delhi, India",
    eventlink: "https://meet.google.com/nji-cadc-mxn",
      isLatest: false,
  },
    {
    id: 13,
    title: "Industry Talk by Ms. Sarah Nawaz",
    type: "seminar",
    displayDate: "October 21, 2025",
    date: "2025-10-21",
    description: "Title: From Academia to Industry: Bridging Research and Real-World Impact.",
    affiliation: "Scientist I, Thermo Fisher Scientific, Bangalore, India.",
    eventlink: "https://meet.google.com/nji-cadc-mxn",
      isLatest: false,
  },
  {
    id: 12,
    title: "International Conference and Workshop on Single-Molecule Biophysics 2026",
    type: "conference",
    displayDate: "January 19-23, 2026",
    date: "2026-01-19",
    organizer: "Dr. Gunjan Mehta, Indian Institute of Technology Hyderabad, India.",
    description: "For more details, please visit the conference website.",
    link: "https://www.simbio2026.com/",
    registrationOpen: "1st June 2025",
    isLatest: true,
  },
  {
    id: 11,
    title: "BioAI Omics Workshop: Foundation & Practice",
    type: "workshop",
    displayDate: "November 8 - 30, 2025",
    date: "2025-11-08",
    description: "A hands-on workshop on the foundation and practice of AI in Omics.",
    organizer: "Dr. Abhishek Subramanian and Dr. Rahul Kumar, Department of Biotechnology, IIT Hyderabad",
    registrationLink: "https://docs.google.com/forms/d/e/1FAIpQLSevqPjHAAmHY65YXwctMu-VUSKrTEiq7s_i-hTCyWr5JXvxfQ/viewform",
    flyerLink: "/events/POSTER_WORKSHOP-6.pdf",
    isLatest: true,
  },
  {
    id: 10,
    title: "Industry Talk Webinar",
    type: "seminar",
    displayDate: "October 14, 2025",
    date: "2025-10-14",
    description: "Career Pathways in Biotechnology: Beyond Academia by Shreya Malik",
  },
  {
    id: 9,
    title: "Biotech Industry Meet 2025",
    type: "meet",
    displayDate: "September 1st, 2025",
    date: "2025-09-01",
    description: "We are pleased to announce a Biotech Industry Meet 2025.",
    link: "/department_website/events/BIM_2025.pdf",
  },
  {
    id: 8,
    title: "Seminar by Prof. Jeremy Simpson",
    type: "seminar",
    displayDate: "August 29th, 2025",
    date: "2025-08-29",
    affiliation: "College of Science, University College Dublin, Ireland",
  },
  {
    id: 7,
    title: "Talk by Prof. Sachin Kotak",
    type: "seminar",
    displayDate: "August 20th, 2025",
    date: "2025-08-20",
    topic: "Understanding the mechanisms of nuclear envelope disassembly and cytokinesis in animal cells.",
    affiliation: "IISc Bangalore",
  },
  {
    id: 6,
    title: "Workshop with Hands-on Activity: Pharma and Biopharma",
    type: "workshop",
    displayDate: "August 8th, 2025",
    date: "2025-08-08",
  },
  {
    id: 5,
    title: "Orientation Hour 2025",
    type: "event",
    displayDate: "July 30th, 2025",
    date: "2025-07-30",
    description: "Organized by the Biotech Society, Dept. of Biotechnology, IITH, extending a warm welcome to all freshers of batch 2025.",
  },
  {
    id: 4,
    title: "Webinar by Aganitha Cognitive Solutions",
    type: "seminar",
    displayDate: "July 29th, 2025",
    date: "2025-07-29",
    topic: "DISTILL, advanced AI-powered transcriptomics analysis platform, built for deep single-cell insights",
  },
  {
    id: 3,
    title: "Talk by Dr. Ravi K Marreddy",
    type: "seminar",
    displayDate: "July 22nd, 2025",
    date: "2025-07-22",
    topic: "Development of Novel Therapeutic Strategies against Clostridioides difficile infections",
    affiliation: "Addition Therapeutics (USA)",
  },
  {
    id: 2,
    title: "5-day Online Workshop on Computational Methods in Advanced & Precision Oncology",
    type: "workshop",
    displayDate: "April 7-11, 2025",
    date: "2025-04-07",
  },
  {
    id: 1,
    title: "Image Processing and Data Analysis using ImageJ",
    type: "workshop",
    displayDate: "February 24-28, 2025",
    date: "2025-02-24",
  },
];
