// src/pages/Biotechsociety.jsx
import { useState } from "react";
import { Users, Target, Eye, Calendar, Mic, FlaskConical, BookOpen, Newspaper } from "lucide-react";

const Biotechsociety = () => {

  // --- Society Members Data ---
  const members = [
    {
      name: "Ashwath Kumar B",
      post: "President",
      year: "",
      course: " M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/AshwathKumarB.webp",
    },                                                      
     {
      name: "Tholkappian R",
      post: "Vice President",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
   
      img: "/society/TholkappianR.webp",
    },
     {
      name: "Amritha Varshini S",
      post: "Treasurer",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/AmrithaVarshiniS.webp",
    },
     {
      name: "Keerthana K",
      post: "Event Head",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/KeerthanaK.webp",
    },
     {
      name: " Yashika Shadija",
      post: "Journal Club Head",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/YashikaShadija.jpeg",
    },
     {
      name: "Harshita Bansal",
      post: "Design Head",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/HarshitaBansal.jpg",
    },
      {
      name: "Vasistha Krishna C",
      post: "Media & Content Head",
      year: "",
      course: "B.Tech. Biotechnology and Bioinformaticsy",
      dept: "Deptartment of Biotechnology",
      img: "/society/VasisthaKrishnaC.jpeg",
    },
       {
      name: "Prachi Tailor",
      post: "PR and Outreach Head",
      year: "",
      course: "M.Tech. Medical Biotechnology",
      dept: "Deptartment of Biotechnology",
      img: "/society/prachitailor.jpg",
    },
    //  {
    //   name: "aaa",
    //   post: "Secretary",
    //   year: "0000000000",
    //   course: " Biotechnology",
    //   dept: "Biotech Dept",
    //   img: "/images/members/qwetry.jpg",
    // }
  ];

  const pastEvents = [
    { date: "Sep 10, 2025", title: "PR & Outreach Session", description: "A walkthrough on 'What after a PhD?' by Dr. Abhishek Subramanian.", category: "PR & Outreach", icon: Mic },
    { date: "Sep 17, 2025", title: "Journal Club Session", description: "Mr. Gokul Raj (M.Tech 1st Year) presented on 'Synthetic genetic circuits...'", category: "Journal Club", icon: FlaskConical },
    { date: "Sep 08, 2025", title: "Teacher's Day 2025", description: "Celebrated and honored the faculty of the department.", category: "Fun Event", icon: Calendar },
    { date: "Sep 03, 2025", title: "Journal Club Session", description: "Mr. Divyesh Pant (M.Tech 2nd Year) on 'Predicting antimicrobial resistance in Pseudomonas...'", category: "Journal Club", icon: FlaskConical },
    { date: "Aug 20, 2025", title: "Journal Club Session", description: "Mr. Suriyaraj S A S (M.Tech 2nd Year) on 'Structural dynamics of DNA unwinding...'", category: "Journal Club", icon: FlaskConical },
    { date: "Aug 18, 2025", title: "Freshers' Eve 2k25", description: "A warm welcome event for the new batch of students.", category: "Fun Event", icon: Calendar },
    { date: "Aug 06, 2025", title: "Journal Club Session", description: "Dr. Anamika Bhargava on 'Beyond the Lab: The Critical Skills Every Researcher Needs'.", category: "Journal Club", icon: FlaskConical },
    { date: "Jul 30, 2025", title: "Orientation Hour 2025", description: "An introductory session for the incoming batch of 2025.", category: "Fun Event", icon: Calendar },
    { date: "Apr 07, 2025", title: "World Health Day 2025", description: "Activities and awareness campaigns for World Health Day.", category: "Fun Event", icon: Calendar },
    { date: "Apr 02, 2025", title: "Journal Club Session", description: "Mr. Ashwath Kumar B (M.Tech 2nd Year) on 'Dopamine-conjugated extracellular vesicles...'", category: "Journal Club", icon: FlaskConical },
    { date: "Feb 26, 2025", title: "Journal Club Session", description: "Ms. Nikitha Thomas (PhD 2nd Year) on 'Chromatin damage generated by DNA intercalators...'", category: "Journal Club", icon: FlaskConical },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Hero Section */}
      <section className="relative text-center py-20 px-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-b-3xl shadow-xl mb-16">
        <div className="absolute inset-0 bg-black/30 rounded-b-3xl"></div>
        <div className="relative z-10">
          <h1 className="text-5xl md:text-6xl font-extrabold mb-4 drop-shadow-lg">The Biotech Society</h1>
          <p className="max-w-3xl mx-auto text-lg md:text-xl leading-relaxed drop-shadow-lg">
            Fostering a community of innovation, collaboration, and growth within the Department of Biotechnology.
          </p>
        </div>
      </section>

      <div className="container mx-auto px-4 space-y-24 pb-16">
        {/* Mission & Vision */}
        <section className="grid md:grid-cols-2 gap-10">
          <div className="bg-white/80 backdrop-blur-sm p-8 rounded-2xl shadow-lg border border-white/50 transform hover:-translate-y-2 transition-transform duration-300">
            <div className="flex items-center gap-4 mb-4">
              <div className="p-3 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-full text-white"><Target className="w-6 h-6" /></div>
              <h2 className="text-2xl font-bold text-gray-800">Our Mission</h2>
            </div>
            <p className="text-gray-700 leading-relaxed">
              To cultivate an inclusive, collaborative, and dynamic community that integrates academic excellence, cultural vibrancy, and professional development, supporting students through initiatives in science, culture, networking, and career building.
            </p>
          </div>
          <div className="bg-white/80 backdrop-blur-sm p-8 rounded-2xl shadow-lg border border-white/50 transform hover:-translate-y-2 transition-transform duration-300">
            <div className="flex items-center gap-4 mb-4">
              <div className="p-3 bg-gradient-to-br from-green-500 to-teal-500 rounded-full text-white"><Eye className="w-6 h-6" /></div>
              <h2 className="text-2xl font-bold text-gray-800">Vision for 2025</h2>
            </div>
            <p className="text-gray-700 leading-relaxed">
              To transform the Biotech Society into a multidimensional, student-led club that becomes a model of departmental unity, scientific exchange, and student empowerment across the academic and cultural spectrum.
            </p>
          </div>
        </section>

        {/* Faculty in Charge Section */}
        <section>
          <h2 className="text-4xl font-bold mb-5 text-center text-transparent bg-clip-text bg-gradient-to-r from-indigo-700 to-purple-700">Faculty in Charge</h2>
          <div className="w-24 h-1 bg-gradient-to-r from-indigo-400 to-purple-400 mx-auto mb-12 rounded-full"></div>
          <div className="flex justify-center">
            <div
              className="bg-white rounded-2xl shadow-lg p-6 text-center transform transition-all duration-300 hover:scale-105 hover:shadow-2xl flex flex-col items-center w-full max-w-sm"
            >
              <img
                src="/faculty/himanshu_joshi.jpeg"
                alt="Dr. Himanshu Joshi"
                className="w-40 h-48 rounded-lg object-cover border-4 border-indigo-200 shadow-md"
              />
              <h3 className="mt-5 text-xl font-semibold text-gray-800">Dr. Himanshu Joshi</h3>
              <p className="text-indigo-600 font-medium">Faculty in Charge</p>
              <p className="text-sm text-gray-500">Department of Biotechnology</p>
            </div>
          </div>
        </section>

        {/* Members Section */}
        <section>
          <h2 className="text-4xl font-bold mb-5 text-center text-transparent bg-clip-text bg-gradient-to-r from-indigo-700 to-purple-700">Society Heads</h2>
          <div className="w-24 h-1 bg-gradient-to-r from-indigo-400 to-purple-400 mx-auto mb-12 rounded-full"></div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            {members.map((m, i) => (
              <div
                key={i}
                className="bg-white rounded-2xl shadow-lg p-6 text-center transform transition-all duration-300 hover:scale-105 hover:shadow-2xl flex flex-col items-center"
              >
                <img
                  src={m.img}
                  alt={m.name}
                  className="w-40 h-48 rounded-lg object-cover border-4 border-white shadow-md mb-4"
                />
                <h3 className="text-xl font-semibold text-gray-800">{m.name}</h3>
                <p className="text-indigo-600 font-medium">{m.post}</p>
                <p className="text-sm text-gray-500 mt-2 flex-grow">{m.course}</p>
                <p className="text-xs text-gray-400">{m.dept}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Newsletter Section */}
        <section className="bg-gradient-to-r from-blue-700 to-indigo-800 text-white rounded-2xl p-10 text-center shadow-2xl">
            <Newspaper className="w-16 h-16 mx-auto mb-4 opacity-80" />
            <h2 className="text-3xl font-bold mb-2">Read Our Newsletter!</h2>
            <p className="mb-6 text-blue-200">Check out the latest issue of BioNiche – Volume 1, Issue 2 (September 2025 Edition).</p>
            <a 
              href="https://heyzine.com/flip-book/7af5c1e7cb.html" 
              target="_blank" 
              rel="noopener noreferrer"
              className="inline-block bg-white text-indigo-700 font-bold py-3 px-8 rounded-full shadow-lg transform hover:scale-105 transition-transform duration-300"
            >
              Read Now
            </a>
        </section>

        {/* Activities Timeline */}
        <section>
          <h2 className="text-4xl font-bold mb-5 text-center text-transparent bg-clip-text bg-gradient-to-r from-indigo-700 to-purple-700">Our Activities</h2>
          <div className="w-24 h-1 bg-gradient-to-r from-indigo-400 to-purple-400 mx-auto mb-12 rounded-full"></div>
          <div className="relative max-w-3xl mx-auto">
            <div className="absolute left-1/2 w-1 bg-gray-200 h-full -translate-x-1/2"></div>
            {pastEvents.sort((a, b) => new Date(b.date) - new Date(a.date)).map((event, index) => {
              const colors = {
                "Journal Club": { border: "border-teal-500", text: "text-teal-600", icon: "text-teal-600" },
                "PR & Outreach": { border: "border-purple-500", text: "text-purple-600", icon: "text-purple-600" },
                "Fun Event": { border: "border-pink-500", text: "text-pink-600", icon: "text-pink-600" },
              };
              const color = colors[event.category] || { border: "border-gray-500", text: "text-gray-600", icon: "text-gray-600" };

              return (
                <div key={index} className="relative mb-8 flex items-center justify-between w-full">
                  <div className={`w-5/12 ${index % 2 === 0 ? 'order-1' : 'order-3'}`}></div>
                  <div className={`z-10 w-12 h-12 bg-white border-4 ${color.border} rounded-full flex items-center justify-center order-2`}>
                    <event.icon className={`w-6 h-6 ${color.icon}`} />
                  </div>
                  <div className={`w-5/12 p-4 bg-white rounded-lg shadow-md border-t-4 ${color.border} ${index % 2 === 0 ? 'order-3' : 'order-1'}`}>
                    <p className={`text-sm font-semibold ${color.text}`}>{event.date}</p>
                    <h3 className="font-bold text-gray-800">{event.title}</h3>
                    <p className="text-sm text-gray-600">{event.description}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </div>
    </div>
  );
};

export default Biotechsociety;
